/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qtblnqqzfnbqtoadpihq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0YmxucXF6Zm5icXRvYWRwaWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NDQ3NzUsImV4cCI6MjA4NTAyMDc3NX0.seR2odAM8UPCJHol-0_-UlAeVRZL1ODL_18Ie-6Jm1A"